In [1]:
# pip install numpy

In [2]:
# @ pip install numpy

In [3]:
# ! pip install numpy

In [4]:
print("hello hi kese ho")

hello hi kese ho


In [5]:
# pip install numpy

In [6]:
import numpy as np

In [7]:
np.__version__

'2.4.6'

In [8]:
lst=list(range(1,20))

In [9]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [10]:
type(lst)

list

In [11]:
arr = np.array(lst)

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr = np.array([2,3,4,6,3,3,5,32,6,8,8,5,8])
# we can create array by this method

In [15]:
arr = np.array([range(1,20)])
# we can automatically define it as array and run it

In [16]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr = np.arange(1,21)
# we can also create arr by using arange keyword

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr = np.zeros(10)

In [22]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
arr = np.ones(10)

In [24]:
arr
print(arr.ndim)

1


In [25]:
arr = np.zeros((5,10))
arr
# this is 2d now 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr = np.zeros((5,10))
print(arr.ndim)

2


In [27]:
arr=np.linspace(1,10,5)
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [28]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
arr = arr.reshape(10,3)
arr
# reshape is used to turn 1d array to 2d array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [30]:
arr = arr.reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [31]:
np.random.randint(1,5,10)
# 1 is starting point here no float no.
# 5 is range at which element should be
# and 10 is no. of elements we want


array([1, 4, 3, 2, 3, 1, 2, 3, 2, 2], dtype=int32)

In [32]:
np.random.randint(1,5,(5,6)) # this will create 2d array


array([[2, 4, 3, 3, 1, 1],
       [4, 1, 3, 2, 3, 1],
       [4, 2, 4, 2, 4, 1],
       [1, 2, 3, 2, 3, 2],
       [2, 3, 4, 1, 2, 4]], dtype=int32)

In [33]:
arr = np.random.random(10)
arr # by using random with random it will include float number
# by using random with randint it will not give float number

array([0.27827479, 0.0292554 , 0.50721951, 0.60061378, 0.54239486,
       0.11577495, 0.38721696, 0.69811001, 0.78358685, 0.88155866])

In [34]:
arr = np.random.random((10,3))
arr

array([[0.87177218, 0.8976091 , 0.63689347],
       [0.49080732, 0.70096661, 0.16371374],
       [0.52655937, 0.54745326, 0.42462932],
       [0.84363697, 0.80770999, 0.03566697],
       [0.28784735, 0.54136509, 0.24210746],
       [0.61273384, 0.38988029, 0.67512294],
       [0.02225182, 0.33573989, 0.14050803],
       [0.69097739, 0.36255765, 0.90894444],
       [0.77234463, 0.28803387, 0.27807813],
       [0.97957806, 0.29892605, 0.13579314]])

In [35]:
arr = np.arange(0,50).reshape(10,5)
arr
# we can create array and turn it into 2d at same time

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
print("number of dimension:-",arr.ndim) # no. of dimension
print("shape of array:-",arr.shape) # shape
print("data types of item:-",arr.dtype) # data type
print("size of array:-",arr.size) # size

number of dimension:- 2
shape of array:- (10, 5)
data types of item:- int64
size of array:- 50


In [37]:
lst = [[1,2,3],[3,5,7]]
lst

[[1, 2, 3], [3, 5, 7]]

In [38]:
arr=np.array(lst)
arr
# list is converted into 2d array

array([[1, 2, 3],
       [3, 5, 7]])

In [39]:
arr = np.arange(0,60).reshape(12,5)

In [40]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [41]:
arr.shape

(12, 5)

In [42]:
arr.T # we transpose the array

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [43]:
arr[0,0]  # first 0 is denote the row
# second 0 denotes column

np.int64(0)

In [44]:
arr[0][0]

np.int64(0)

In [45]:
arr[11][4]

np.int64(59)

In [46]:
arr[-1,-1]

np.int64(59)

In [47]:
arr[11,-1]

np.int64(59)

In [48]:
arr[-1,4]

np.int64(59)

In [49]:
arr[2:4,3:]

array([[13, 14],
       [18, 19]])

In [50]:
arr[7:9,1:3] # this is how we do indexing

array([[36, 37],
       [41, 42]])

In [51]:
arr[8:11,1:4]

array([[41, 42, 43],
       [46, 47, 48],
       [51, 52, 53]])

In [52]:
arr[0:9,3:4] # doing only one column

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [53]:
arr[3:5,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

In [54]:
arr[-1,-1] = 100
arr
# changing an exact value

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [55]:
print("number of dimension:-",arr.ndim) # no. of dimension
print("shape of array:-",arr.shape) # shape
print("data types of item:-",arr.dtype) # data type
print("size of array:-",arr.size) # size

number of dimension:- 2
shape of array:- (12, 5)
data types of item:- int64
size of array:- 60


## 3d array

In [ ]:


arr = np.arange(225).reshape(5,15,3)
# 5 is denoting table
# 15 is row in every table
# 3 is denoting column  in every table
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [60]:
# arr = np.arange(225).reshape(5,9,5)
#arr

In [63]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [64]:
arr[0][0]

array([0, 1, 2])

In [65]:
arr[0][0][0]

np.int64(0)

In [ ]:
arr[-1] # only -1 gives the last table

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [ ]:
arr[-2] # giving second last table

array([[135, 136, 137],
       [138, 139, 140],
       [141, 142, 143],
       [144, 145, 146],
       [147, 148, 149],
       [150, 151, 152],
       [153, 154, 155],
       [156, 157, 158],
       [159, 160, 161],
       [162, 163, 164],
       [165, 166, 167],
       [168, 169, 170],
       [171, 172, 173],
       [174, 175, 176],
       [177, 178, 179]])

In [68]:
arr[0][0]

array([0, 1, 2])

In [ ]:
arr[0:5,0]
# we are taking table from 

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [ ]:
arr[0:5,0:1,0:1] # arr[0:5,0,0]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [75]:
arr[0:5,2:4,0:3]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [76]:
arr[0:5,-1,0]

array([ 42,  87, 132, 177, 222])

In [79]:
arr[0:5,0:15,2:4]

array([[[  2],
        [  5],
        [  8],
        [ 11],
        [ 14],
        [ 17],
        [ 20],
        [ 23],
        [ 26],
        [ 29],
        [ 32],
        [ 35],
        [ 38],
        [ 41],
        [ 44]],

       [[ 47],
        [ 50],
        [ 53],
        [ 56],
        [ 59],
        [ 62],
        [ 65],
        [ 68],
        [ 71],
        [ 74],
        [ 77],
        [ 80],
        [ 83],
        [ 86],
        [ 89]],

       [[ 92],
        [ 95],
        [ 98],
        [101],
        [104],
        [107],
        [110],
        [113],
        [116],
        [119],
        [122],
        [125],
        [128],
        [131],
        [134]],

       [[137],
        [140],
        [143],
        [146],
        [149],
        [152],
        [155],
        [158],
        [161],
        [164],
        [167],
        [170],
        [173],
        [176],
        [179]],

       [[182],
        [185],
        [188],
        [191],
        [194],
        [197],
  

In [ ]:
arr[0:5,0:15,3:5]
# it will show that your shape is this

array([], shape=(5, 15, 0), dtype=int64)

In [81]:
arr[0:5,-1,-1]

array([ 44,  89, 134, 179, 224])

In [86]:
arr[0:5,14:15,-1]

array([[ 44],
       [ 89],
       [134],
       [179],
       [224]])

In [87]:
arr[0:5,-1,2:3]

array([[ 44],
       [ 89],
       [134],
       [179],
       [224]])

In [88]:
arr[0:5,14:15,2:3]

array([[[ 44]],

       [[ 89]],

       [[134]],

       [[179]],

       [[224]]])

In [89]:
print("number of dimension:-",arr.ndim) # no. of dimension
print("shape of array:-",arr.shape) # shape
print("data types of item:-",arr.dtype) # data type
print("size of array:-",arr.size) # size

number of dimension:- 3
shape of array:- (5, 15, 3)
data types of item:- int64
size of array:- 225


In [ ]:
arr[0,-1,-1] = 100 # replaced the last element of first table by 100
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43, 100]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [91]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [ ]:
arr1 = np.array([10, 50, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

arr1.sort() # it will sort the array.
#print(arr1.sort()) # it will return none
#print(arr1) # it will also return the output 
arr1 # it will return the output

Array 1 : [10 50 30 40]
Array 2 : [2 4 6 8]


array([10, 30, 40, 50])

In [ ]:
arr = np.arange(225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [99]:
arr=arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11